{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_0_selenium_a_login", "status": "PASSED", "start_time": 1604655800.3473678, "duration": 1.294924259185791, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 5, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_1_selenium_view_page", "status": "PASSED", "start_time": 1604655801.6433265, "duration": 0.7046740055084229, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 9, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_1_selenium_create_page", "status": "PASSED", "start_time": 1604655802.3488257, "duration": 2.9402856826782227, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 13, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_1_selenium_edit_page", "status": "PASSED", "start_time": 1604655805.289952, "duration": 5.285203218460083, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 17, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_1_selenium_create_comment", "status": "PASSED", "start_time": 1604655810.5759997, "duration": 2.2953693866729736, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 21, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_1_selenium_view_blog", "status": "PASSED", "start_time": 1604655812.8721898, "duration": 0.90071702003479, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 25, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_1_selenium_view_dashboard", "status": "PASSED", "start_time": 1604655813.7741907, "duration": 8.373215436935425, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 29, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_2_selenium_z_log_out", "status": "PASSED", "start_time": 1604655822.1482375, "duration": 0.21161961555480957, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 43, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_0_selenium_a_login", "status": "PASSED", "start_time": 1604655822.424018, "duration": 1.516049861907959, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 5, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_1_selenium_view_page", "status": "PASSED", "start_time": 1604655823.9408815, "duration": 0.6268360614776611, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 9, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_1_selenium_create_page", "status": "PASSED", "start_time": 1604655824.5685298, "duration": 3.1364526748657227, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 13, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_1_selenium_edit_page", "status": "PASSED", "start_time": 1604655827.7058353, "duration": 5.034619331359863, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 17, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_1_selenium_create_comment", "status": "PASSED", "start_time": 1604655832.741325, "duration": 2.031703472137451, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 21, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_1_selenium_view_blog", "status": "PASSED", "start_time": 1604655834.7738423, "duration": 1.4771809577941895, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 25, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_1_selenium_view_dashboard", "status": "PASSED", "start_time": 1604655836.2518423, "duration": 12.791332483291626, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 29, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_2_selenium_z_log_out", "status": "PASSED", "start_time": 1604655849.0439873, "duration": 0.21238493919372559, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 43, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_0_selenium_a_login", "status": "PASSED", "start_time": 1604655849.3118458, "duration": 2.3625104427337646, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 5, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_1_selenium_view_page", "status": "PASSED", "start_time": 1604655851.6755943, "duration": 0.9200940132141113, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 9, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_1_selenium_create_page", "status": "PASSED", "start_time": 1604655852.5965593, "duration": 4.498792886734009, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 13, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_1_selenium_edit_page", "status": "PASSED", "start_time": 1604655857.0961735, "duration": 5.801886796951294, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 17, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_1_selenium_create_comment", "status": "PASSED", "start_time": 1604655862.8988717, "duration": 2.6346027851104736, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 21, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_1_selenium_view_blog", "status": "PASSED", "start_time": 1604655865.5343134, "duration": 1.268244743347168, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 25, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_1_selenium_view_dashboard", "status": "PASSED", "start_time": 1604655866.8034236, "duration": 18.101821184158325, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 29, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_2_selenium_z_log_out", "status": "PASSED", "start_time": 1604655884.9060998, "duration": 0.27884936332702637, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 43, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_0_selenium_a_login", "status": "PASSED", "start_time": 1604655885.2381186, "duration": 3.9695780277252197, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 5, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_1_selenium_view_page", "status": "PASSED", "start_time": 1604655889.208522, "duration": 2.5416476726531982, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 9, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_1_selenium_create_page", "status": "PASSED", "start_time": 1604655891.751012, "duration": 7.020446300506592, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 13, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_1_selenium_edit_page", "status": "PASSED", "start_time": 1604655898.7723231, "duration": 9.208967924118042, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 17, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_1_selenium_create_comment", "status": "PASSED", "start_time": 1604655907.9821877, "duration": 3.36914324760437, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 21, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_1_selenium_view_blog", "status": "PASSED", "start_time": 1604655911.3521585, "duration": 2.2593939304351807, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 25, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_1_selenium_view_dashboard", "status": "FAILED", "start_time": 1604655913.6123753, "duration": 37.010716915130615, "error_msg": "Exception: ('Failed measure: selenium_view_dashboard - TimeoutException', TimeoutException(\"Error in wait_until: Timed out after 30 sec waiting for <selenium.webdriver.support.expected_conditions.visibility_of_element_located object at 0x7f4b9ca7eb50>. \\nLocator: ('class name', 'update-items')\", None, None))", "error_trace": "File \"/usr/local/lib/python3.8/dist-packages/_pytest/runner.py\", line 310, in from_call\n    result = func()  # type: Optional[TResult]\n\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/runner.py\", line 256, in <lambda>\n    lambda: ihook(item=item, **kwds), when=when, reraise=reraise\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/hooks.py\", line 286, in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/manager.py\", line 93, in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/manager.py\", line 84, in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/callers.py\", line 208, in _multicall\n    return outcome.get_result()\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/callers.py\", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/runner.py\", line 171, in pytest_runtest_call\n    raise e\n\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/runner.py\", line 163, in pytest_runtest_call\n    item.runtest()\n\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/python.py\", line 1627, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/hooks.py\", line 286, in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/manager.py\", line 93, in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/manager.py\", line 84, in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/callers.py\", line 208, in _multicall\n    return outcome.get_result()\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/callers.py\", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/python.py\", line 184, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n\n  File \"/dc-app-performance-toolkit/app/selenium_ui/confluence_ui.py\", line 31, in test_1_selenium_view_dashboard\n    modules.view_dashboard(confluence_webdriver, confluence_datasets)\n\n  File \"/dc-app-performance-toolkit/app/selenium_ui/confluence/modules.py\", line 81, in view_dashboard\n    measure()\n\n  File \"/dc-app-performance-toolkit/app/selenium_ui/conftest.py\", line 120, in wrapper\n    raise Exception(error_msg, full_exception)", "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 29, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_2_selenium_z_log_out", "status": "PASSED", "start_time": 1604655958.5499694, "duration": 4.153005838394165, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 43, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_0_selenium_a_login", "status": "PASSED", "start_time": 1604655962.7524998, "duration": 15.443334102630615, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 5, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_1_selenium_view_page", "status": "PASSED", "start_time": 1604655978.1966822, "duration": 3.4561405181884766, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 9, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_1_selenium_create_page", "status": "PASSED", "start_time": 1604655981.6536908, "duration": 32.8521888256073, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 13, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_1_selenium_edit_page", "status": "FAILED", "start_time": 1604656014.5067463, "duration": 38.01607966423035, "error_msg": "Exception: ('Failed measure: selenium_edit_page - Exception', Exception('Failed measure: selenium_edit_page:open_create_page_editor - TimeoutException', TimeoutException(\"Error in wait_until: Timed out after 30 sec waiting for one of the conditions: \\n Condition: <selenium.webdriver.support.expected_conditions.text_to_be_present_in_element object at 0x7f4b9c9e0d60> Locator: ('class name', 'status-indicator-message')\\n Condition: <selenium.webdriver.support.expected_conditions.text_to_be_present_in_element object at 0x7f4b9c9e0d30> Locator: ('class name', 'status-indicator-message')\\n\", None, None)))", "error_trace": "File \"/usr/local/lib/python3.8/dist-packages/_pytest/runner.py\", line 310, in from_call\n    result = func()  # type: Optional[TResult]\n\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/runner.py\", line 256, in <lambda>\n    lambda: ihook(item=item, **kwds), when=when, reraise=reraise\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/hooks.py\", line 286, in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/manager.py\", line 93, in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/manager.py\", line 84, in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/callers.py\", line 208, in _multicall\n    return outcome.get_result()\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/callers.py\", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/runner.py\", line 171, in pytest_runtest_call\n    raise e\n\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/runner.py\", line 163, in pytest_runtest_call\n    item.runtest()\n\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/python.py\", line 1627, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/hooks.py\", line 286, in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/manager.py\", line 93, in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/manager.py\", line 84, in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/callers.py\", line 208, in _multicall\n    return outcome.get_result()\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/callers.py\", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/python.py\", line 184, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n\n  File \"/dc-app-performance-toolkit/app/selenium_ui/confluence_ui.py\", line 19, in test_1_selenium_edit_page\n    modules.edit_confluence_page(confluence_webdriver, confluence_datasets)\n\n  File \"/dc-app-performance-toolkit/app/selenium_ui/confluence/modules.py\", line 130, in edit_confluence_page\n    measure()\n\n  File \"/dc-app-performance-toolkit/app/selenium_ui/conftest.py\", line 120, in wrapper\n    raise Exception(error_msg, full_exception)", "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 17, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_1_selenium_create_comment", "status": "FAILED", "start_time": 1604656067.9633374, "duration": 38.37699007987976, "error_msg": "Exception: ('Failed measure: selenium_create_comment - Exception', Exception('Failed measure: selenium_create_comment:write_comment - TimeoutException', TimeoutException(\"Error in wait_until: Timed out after 30 sec waiting for <selenium.webdriver.support.expected_conditions.frame_to_be_available_and_switch_to_it object at 0x7f4b9c9e37f0>. \\nLocator: ('id', 'wysiwygTextarea_ifr')\", None, None)))", "error_trace": "File \"/usr/local/lib/python3.8/dist-packages/_pytest/runner.py\", line 310, in from_call\n    result = func()  # type: Optional[TResult]\n\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/runner.py\", line 256, in <lambda>\n    lambda: ihook(item=item, **kwds), when=when, reraise=reraise\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/hooks.py\", line 286, in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/manager.py\", line 93, in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/manager.py\", line 84, in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/callers.py\", line 208, in _multicall\n    return outcome.get_result()\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/callers.py\", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/runner.py\", line 171, in pytest_runtest_call\n    raise e\n\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/runner.py\", line 163, in pytest_runtest_call\n    item.runtest()\n\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/python.py\", line 1627, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/hooks.py\", line 286, in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/manager.py\", line 93, in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/manager.py\", line 84, in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/callers.py\", line 208, in _multicall\n    return outcome.get_result()\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/callers.py\", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/python.py\", line 184, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n\n  File \"/dc-app-performance-toolkit/app/selenium_ui/confluence_ui.py\", line 23, in test_1_selenium_create_comment\n    modules.create_comment(confluence_webdriver, confluence_datasets)\n\n  File \"/dc-app-performance-toolkit/app/selenium_ui/confluence/modules.py\", line 153, in create_comment\n    measure()\n\n  File \"/dc-app-performance-toolkit/app/selenium_ui/conftest.py\", line 120, in wrapper\n    raise Exception(error_msg, full_exception)", "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 21, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_1_selenium_view_blog", "status": "PASSED", "start_time": 1604656125.4454033, "duration": 7.170258522033691, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 25, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_1_selenium_view_dashboard", "status": "FAILED", "start_time": 1604656132.616482, "duration": 52.96358299255371, "error_msg": "Exception: ('Failed measure: selenium_view_dashboard - TimeoutException', TimeoutException(\"Error in wait_until: Timed out after 30 sec waiting for <selenium.webdriver.support.expected_conditions.visibility_of_element_located object at 0x7f4b9c9afac0>. \\nLocator: ('class name', 'update-items')\", None, None))", "error_trace": "File \"/usr/local/lib/python3.8/dist-packages/_pytest/runner.py\", line 310, in from_call\n    result = func()  # type: Optional[TResult]\n\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/runner.py\", line 256, in <lambda>\n    lambda: ihook(item=item, **kwds), when=when, reraise=reraise\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/hooks.py\", line 286, in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/manager.py\", line 93, in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/manager.py\", line 84, in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/callers.py\", line 208, in _multicall\n    return outcome.get_result()\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/callers.py\", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/runner.py\", line 171, in pytest_runtest_call\n    raise e\n\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/runner.py\", line 163, in pytest_runtest_call\n    item.runtest()\n\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/python.py\", line 1627, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/hooks.py\", line 286, in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/manager.py\", line 93, in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/manager.py\", line 84, in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/callers.py\", line 208, in _multicall\n    return outcome.get_result()\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/callers.py\", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n\n  File \"/usr/local/lib/python3.8/dist-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/python.py\", line 184, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n\n  File \"/dc-app-performance-toolkit/app/selenium_ui/confluence_ui.py\", line 31, in test_1_selenium_view_dashboard\n    modules.view_dashboard(confluence_webdriver, confluence_datasets)\n\n  File \"/dc-app-performance-toolkit/app/selenium_ui/confluence/modules.py\", line 81, in view_dashboard\n    measure()\n\n  File \"/dc-app-performance-toolkit/app/selenium_ui/conftest.py\", line 120, in wrapper\n    raise Exception(error_msg, full_exception)", "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 29, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
{"test_suite": "selenium_ui.confluence_ui", "test_case": "test_2_selenium_z_log_out", "status": "PASSED", "start_time": 1604656195.0917406, "duration": 3.5646214485168457, "error_msg": null, "error_trace": null, "extras": {"filename": "selenium_ui/confluence_ui.py", "lineno": 43, "assertions": []}, "assertions": [], "subsamples": [], "path": []}
